In [1]:
import pandas as pd

In [2]:
txt_path ="D:/danmu.txt"

data_table = pd.read_csv(txt_path,sep=',',names= ['start_point','b','c','time','d','e','f','g','comments'])

In [219]:
# 把 文本写出 到 txt 文件中
f = open('D:/ciyun.txt','w+',encoding = 'utf-8')

text  = data_table.comments.to_list()
text  = str(text).strip('[').strip(']')

f.write(text)
f.close()

In [6]:
import datetime

In [8]:
# 对我们有用的信息只有三列
new_tables = data_table[['start_point','d','comments']]
new_tables

      start_point           d               comments
0         330.260  1596383999                我已经找到了！
1         403.993  1596383999                      哇
2         286.876  1596383998                   辛苦了！
3         409.964  1596383998                     泪目
4          16.320  1596383998                我找到了！！！
...           ...         ...                    ...
6995       63.173  1596778134  啊小何你怎么可能把600万人凑到一起拍照呢
6996      406.817  1596778118                    我滴天
6997      406.974  1596778080                   全体起立
6998       57.325  1596778038                     泪目
6999       47.926  1596778012                 我见证了他火

[7000 rows x 3 columns]

In [11]:
# 将时间戳转化为日期
new_tables['comment_times'] = new_tables.d.apply(lambda x :datetime.datetime.fromtimestamp(x).strftime('%Y-%m-%d %H:%M:%S'))

D:\program fIle2\Anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [12]:
new_tables

      start_point           d               comments        comment_times
0         330.260  1596383999                我已经找到了！  2020-08-02 23:59:59
1         403.993  1596383999                      哇  2020-08-02 23:59:59
2         286.876  1596383998                   辛苦了！  2020-08-02 23:59:58
3         409.964  1596383998                     泪目  2020-08-02 23:59:58
4          16.320  1596383998                我找到了！！！  2020-08-02 23:59:58
...           ...         ...                    ...                  ...
6995       63.173  1596778134  啊小何你怎么可能把600万人凑到一起拍照呢  2020-08-07 13:28:54
6996      406.817  1596778118                    我滴天  2020-08-07 13:28:38
6997      406.974  1596778080                   全体起立  2020-08-07 13:28:00
6998       57.325  1596778038                     泪目  2020-08-07 13:27:18
6999       47.926  1596778012                 我见证了他火  2020-08-07 13:26:52

[7000 rows x 4 columns]

In [16]:
# 将 start_point 秒 转化 为 分秒
new_tables['times_point'] = new_tables.start_point.apply(lambda x: datetime.timedelta(seconds =int(x)))

D:\program fIle2\Anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [17]:
new_tables

,start_point,d,comments,comment_times,times_point
0,330.260,1596383999,我已经找到了！,2020-08-02 23:59:59,00:05:30
1,403.993,1596383999,哇,2020-08-02 23:59:59,00:06:43
2,286.876,1596383998,辛苦了！,2020-08-02 23:59:58,00:04:46
3,409.964,1596383998,泪目,2020-08-02 23:59:58,00:06:49
4,16.320,1596383998,我找到了！！！,2020-08-02 23:59:58,00:00:16
...,...,...,...,...,...
6995,63.173,1596778134,啊小何你怎么可能把600万人凑到一起拍照呢,2020-08-07 13:28:54,00:01:03
6996,406.817,1596778118,我滴天,2020-08-07 13:28:38,00:06:46
6997,406.974,1596778080,全体起立,2020-08-07 13:28:00,00:06:46
6998,57.325,1596778038,泪目,2020-08-07 13:27:18,00:00:57
6999,47.926,1596778012,我见证了他火,2020-08-07 13:26:52,00:00:47

In [20]:
tranform_table = new_tables
tranform_table['times_point'] = tranform_table.times_point.apply(lambda x:str(x)[3:])
tranform_table['date_days'] = tranform_table.comment_times.apply(lambda x:datetime.datetime.fromisoformat(x).strftime("%Y-%m-%d"))
tranform_table['date_hours_'] = tranform_table.comment_times.apply(lambda x:datetime.datetime.fromisoformat(x).strftime("%H:%M:%S"))
tranform_table

D:\program fIle2\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

D:\program fIle2\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
D:\program fIle2\Anaconda\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,start_point,d,comments,comment_times,times_point,date_days,date_hours_
0,330.260,1596383999,我已经找到了！,2020-08-02 23:59:59,:05:30,2020-08-02,23:59:59
1,403.993,1596383999,哇,2020-08-02 23:59:59,:06:43,2020-08-02,23:59:59
2,286.876,1596383998,辛苦了！,2020-08-02 23:59:58,:04:46,2020-08-02,23:59:58
3,409.964,1596383998,泪目,2020-08-02 23:59:58,:06:49,2020-08-02,23:59:58
4,16.320,1596383998,我找到了！！！,2020-08-02 23:59:58,:00:16,2020-08-02,23:59:58
...,...,...,...,...,...,...,...
6995,63.173,1596778134,啊小何你怎么可能把600万人凑到一起拍照呢,2020-08-07 13:28:54,:01:03,2020-08-07,13:28:54
6996,406.817,1596778118,我滴天,2020-08-07 13:28:38,:06:46,2020-08-07,13:28:38
6997,406.974,1596778080,全体起立,2020-08-07 13:28:00,:06:46,2020-08-07,13:28:00
6998,57.325,1596778038,泪目,2020-08-07 13:27:18,:00:57,2020-08-07,13:27:18
6999,47.926,1596778012,我见证了他火,2020-08-07 13:26:52,:00:47,2020-08-07,13:26:52

In [21]:
# 首先，以 d 为准进行排序
tranform_table.sort_values(by ='d')

,start_point,d,comments,comment_times,times_point,date_days,date_hours_
997,284.364,1596383481,辛苦了！,2020-08-02 23:51:21,:04:44,2020-08-02,23:51:21
999,26.111,1596383481,辛苦了,2020-08-02 23:51:21,:00:26,2020-08-02,23:51:21
998,7.096,1596383481,有生之年,2020-08-02 23:51:21,:00:07,2020-08-02,23:51:21
996,243.961,1596383483,大制作,2020-08-02 23:51:23,:04:03,2020-08-02,23:51:23
995,459.623,1596383483,浪漫的！,2020-08-02 23:51:23,:07:39,2020-08-02,23:51:23
...,...,...,...,...,...,...,...
6004,407.040,1596868267,升华了,2020-08-08 14:31:07,:06:47,2020-08-08,14:31:07
6003,412.663,1596868273,升华了,2020-08-08 14:31:13,:06:52,2020-08-08,14:31:13
6002,426.891,1596868287,升华了,2020-08-08 14:31:27,:07:06,2020-08-08,14:31:27
6001,444.188,1596868341,天哪，小何同学辛苦了(≧∇≦)/,2020-08-08 14:32:21,:07:24,2020-08-08,14:32:21
6000,422.140,1596868448,理科生的浪漫,2020-08-08 14:34:08,:07:02,2020-08-08,14:34:08

In [197]:
# 以评论时间顺序进行绘图

times_count = tranform_table.sort_values(by ='d')

times_count['Date'] = pd.to_datetime(times_count.comment_times)
times_count = times_count.set_index("Date")
times_count = times_count.resample('30T').count()
times_count


# times_count = tranform_table.group('comment_times').resample('30S').sum()

,start_point,d,comments,comment_times,times_point,date_days,date_hours_
Date,,,,,,,
2020-08-02 23:30:00,1000,1000,1000,1000,1000,1000,1000
2020-08-03 00:00:00,0,0,0,0,0,0,0
2020-08-03 00:30:00,0,0,0,0,0,0,0
2020-08-03 01:00:00,0,0,0,0,0,0,0
2020-08-03 01:30:00,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...
2020-08-08 12:30:00,48,48,48,48,48,48,48
2020-08-08 13:00:00,21,21,21,21,21,21,21
2020-08-08 13:30:00,20,20,20,20,20,20,20
2020-08-08 14:00:00,33,33,33,33,33,33,33
2020-08-08 14:30:00,7,7,7,7,7,7,7

In [198]:
times_count['count'] = times_count['start_point'].cumsum()

In [199]:
times_count

,start_point,d,comments,comment_times,times_point,date_days,date_hours_,count
Date,,,,,,,,
2020-08-02 23:30:00,1000,1000,1000,1000,1000,1000,1000,1000
2020-08-03 00:00:00,0,0,0,0,0,0,0,1000
2020-08-03 00:30:00,0,0,0,0,0,0,0,1000
2020-08-03 01:00:00,0,0,0,0,0,0,0,1000
2020-08-03 01:30:00,0,0,0,0,0,0,0,1000
...,...,...,...,...,...,...,...,...
2020-08-08 12:30:00,48,48,48,48,48,48,48,6919
2020-08-08 13:00:00,21,21,21,21,21,21,21,6940
2020-08-08 13:30:00,20,20,20,20,20,20,20,6960
2020-08-08 14:00:00,33,33,33,33,33,33,33,6993
2020-08-08 14:30:00,7,7,7,7,7,7,7,7000

In [37]:
from pyecharts import options as opts
from pyecharts.charts import Line

In [217]:
# str(times_count.index.to_list()[0].isoformat())
a = times_count['count'].to_list()

In [221]:
# 绘制曲线走势图

c = (
    Line()
    .add_xaxis([str(i.isoformat()) for i in times_count.index.to_list()])
    .add_yaxis('评论数量',a,is_smooth=True,color = 'blue')
    .set_series_opts(
        areastyle_opts=opts.AreaStyleOpts(opacity=0.5),
        label_opts=opts.LabelOpts(is_show=False),
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="《【何同学】我拍了一张600万人的合影...》时间线评论数量变化"),
        xaxis_opts=opts.AxisOpts(
            axistick_opts=opts.AxisTickOpts(is_align_with_label=True),
            is_scale=False,
            boundary_gap=False,
            
            name_rotate = 45
        
        ),
        
        legend_opts = opts.LegendOpts(pos_left = 'right')
        
        
    )
    .render("D:/line_areastyle_boundary_gap.html")
)

D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)

In [161]:
trans = tranform_table.sort_values(by=['d']).set_index('comment_times')
trans.index = pd.to_datetime(trans.index)
trans[trans['date_days']=='2020-08-02'].resample('30T').count().index.to_list()

[Timestamp('2020-08-02 23:30:00', freq='30T')]

In [131]:
date_list = sorted(set(trans['date_days'].to_list()))
date_list

['2020-08-02',
 '2020-08-03',
 '2020-08-04',
 '2020-08-05',
 '2020-08-06',
 '2020-08-07',
 '2020-08-08']

In [133]:
# 绘制时间线
from pyecharts.charts import Bar, Timeline
from pyecharts.faker import Faker
import random

tl = Timeline()
for i in date_list:
    bar = (
        Bar()
        .add_xaxis([str(i.isoformat()).split('T')[-1] for i in trans[trans['date_days']==str(i)].resample('30T').count().index.to_list()])
        .add_yaxis("Comment Count", trans[trans['date_days']==str(i)].resample('30T').count().d.to_list(),color = random.choice(['orange','blue','red']))
        
        .set_global_opts(title_opts=opts.TitleOpts("{}评论时间分布图".format(i)))
    )
    tl.add(bar, "{}年".format(str(i)))
tl.render("D:/timeline_bar.html")

D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\composite_charts\timeline.py:12: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)
D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)
D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)
D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)
D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)
D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)
D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)
D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)

'D:\\timeline_bar.html'

In [163]:
trans['times_point'] = trans['times_point'].apply(lambda x :str(x)[1:])
trans = trans.sort_values(by = 'times_point')
trans

,start_point,d,comments,times_point,date_days,date_hours_
comment_times,,,,,,
2020-08-06 16:16:54,0.164,1596701814,839w了,00:00,2020-08-06,16:16:54
2020-08-03 23:31:02,0.504,1596468662,500w贺电！！！,00:00,2020-08-03,23:31:02
2020-08-03 23:45:00,0.120,1596469500,很时尚,00:00,2020-08-03,23:45:00
2020-08-05 21:28:28,0.523,1596634108,找到了！！！！！,00:00,2020-08-05,21:28:28
2020-08-07 15:49:03,0.916,1596786543,惊讶 感动 震撼 到不知道说什么,00:00,2020-08-07,15:49:03
...,...,...,...,...,...,...
2020-08-06 23:54:19,476.011,1596729259,我也没找到,07:56,2020-08-06,23:54:19
2020-08-06 19:12:24,476.083,1596712344,下期见,07:56,2020-08-06,19:12:24
2020-08-06 23:54:19,476.011,1596729259,我也没找到,07:56,2020-08-06,23:54:19
2020-08-04 21:10:48,477.000,1596546648,感动,07:57,2020-08-04,21:10:48
2020-08-02 23:52:02,477.000,1596383522,爱了爱了,07:57,2020-08-02,23:52:02

In [165]:
trans.times_point = pd.to_datetime(trans.times_point)
trans

,start_point,d,comments,times_point,date_days,date_hours_
comment_times,,,,,,
2020-08-06 16:16:54,0.164,1596701814,839w了,2020-08-08 00:00:00,2020-08-06,16:16:54
2020-08-03 23:31:02,0.504,1596468662,500w贺电！！！,2020-08-08 00:00:00,2020-08-03,23:31:02
2020-08-03 23:45:00,0.120,1596469500,很时尚,2020-08-08 00:00:00,2020-08-03,23:45:00
2020-08-05 21:28:28,0.523,1596634108,找到了！！！！！,2020-08-08 00:00:00,2020-08-05,21:28:28
2020-08-07 15:49:03,0.916,1596786543,惊讶 感动 震撼 到不知道说什么,2020-08-08 00:00:00,2020-08-07,15:49:03
...,...,...,...,...,...,...
2020-08-06 23:54:19,476.011,1596729259,我也没找到,2020-08-08 07:56:00,2020-08-06,23:54:19
2020-08-06 19:12:24,476.083,1596712344,下期见,2020-08-08 07:56:00,2020-08-06,19:12:24
2020-08-06 23:54:19,476.011,1596729259,我也没找到,2020-08-08 07:56:00,2020-08-06,23:54:19
2020-08-04 21:10:48,477.000,1596546648,感动,2020-08-08 07:57:00,2020-08-04,21:10:48
2020-08-02 23:52:02,477.000,1596383522,爱了爱了,2020-08-08 07:57:00,2020-08-02,23:52:02

In [190]:
# trans.set_index('times_point').resample("30T").d.count()
# trans.set_index('times_point').resample("30T").d.count().to_list()
# trans.set_index('times_point').index.to_list()

#A = [str(i .isoformat()).split('T')[-1] for i in trans.set_index('times_point').index.to_list()]
# A = [trans.times_point.to_list()]
# A

trans1 = trans.set_index('times_point')
trans2  = trans1.resample('30T').start_point.count()
trans2.index.to_list()

[Timestamp('2020-08-08 00:00:00', freq='30T'),
 Timestamp('2020-08-08 00:30:00', freq='30T'),
 Timestamp('2020-08-08 01:00:00', freq='30T'),
 Timestamp('2020-08-08 01:30:00', freq='30T'),
 Timestamp('2020-08-08 02:00:00', freq='30T'),
 Timestamp('2020-08-08 02:30:00', freq='30T'),
 Timestamp('2020-08-08 03:00:00', freq='30T'),
 Timestamp('2020-08-08 03:30:00', freq='30T'),
 Timestamp('2020-08-08 04:00:00', freq='30T'),
 Timestamp('2020-08-08 04:30:00', freq='30T'),
 Timestamp('2020-08-08 05:00:00', freq='30T'),
 Timestamp('2020-08-08 05:30:00', freq='30T'),
 Timestamp('2020-08-08 06:00:00', freq='30T'),
 Timestamp('2020-08-08 06:30:00', freq='30T'),
 Timestamp('2020-08-08 07:00:00', freq='30T'),
 Timestamp('2020-08-08 07:30:00', freq='30T')]

In [192]:
c = (
    Bar()
    .add_xaxis([str(i .isoformat()).split('T')[-1] for i in trans2.index.to_list()])
    .add_yaxis("评论数量",trans1.resample('30T').start_point.count().to_list())

    .set_global_opts(title_opts=opts.TitleOpts(title="《【何同学】我拍了一张600万人的合影...》弹幕分布"),
                    legend_opts = opts.LegendOpts(pos_left = 'right'))
    .set_series_opts(
        label_opts=opts.LabelOpts(is_show=False),
        markpoint_opts=opts.MarkPointOpts(
            data=[
                opts.MarkPointItem(type_="max", name="最大值"),
                opts.MarkPointItem(type_="min", name="最小值"),
                opts.MarkPointItem(type_="average", name="平均值"),
            ]
        ),
    )
    .render("D:/bar_markpoint_type.html")
)

D:\program fIle2\Anaconda\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)